### ISSUE TITLE
Evo3m UART interface couldn't find the Evo.

### ISSUE THREAD

**Issue by Mfa1m3** [Terabee/sample_codes#11]
sudo i2cdetect -y 1
detects the sensor with address 31, but when running "python3 Evo_single_point_display_range_py3.py", the sensor is not detected. I get the following error.

Starting Evo data streaming
Scanning all live ports on this PC
Sorry couldn't find the Evo. Exiting.

**Comment by pl-kabaradjian** [comment]
Hello @Mfa1m3 

Unfortunately, "Evo_single_point_display_range_py3.py" is for serial communication only (UART). We do have i2c code samples for Arduino however.

Feel free to contact our support directly on our website.

Cheers

**Comment by Mfa1m3** [comment]
Hello @pl-kabaradjian 

I tried the sensor on Ardunio and it works well. 

But unfortunately, Communicating to sensor via UART on raspberry pi is also not being recognized and giving the same error.

Starting Evo data streaming
Scanning all live ports on this PC
Sorry couldn't find the Evo. Exiting.

**Comment by EXPX3** [comment]
Hi I looked into Terabee/sample_codes/Python/Evo_single_point_display_range_py3.py file, 

When i tried via UART,

I see that the function findEvo( ) is returning NULL because of the line " if "5740" in p[2]: " as the ports list, from " ports = list(serial.tools.list_ports.comports( )) ", has only one value inside. 

what is "5740" here?

**Comment by EXPX3** [comment]
@Mfa1m3 @pl-kabaradjian 
By default raspberrypi 3b+ serial ports are set to bluetooth. I found multiple methods to get around this.
1. we can disable bluetooth by inserting these lines, <bdtoverlay=pi3-disable-btin> and<dtoverlay=pi3-miniuart-bt> (without the <>signs) in the /boot/config.txt. Also modify the function findEvo( ): as below
def findEvo():
    print('Scanning all live ports on this PC')
    ports = list(serial.tools.list_ports.comports())
    for p in ports:
        return p[0]
2. without need to disabling bluetooth just modify the function findEvo( ) as follows
 def findEvo():
    print('Scanning all live ports on this PC')
    return '/dev/serial0'

[ref](https://www.elinux.org/Serial_port_programming)

**Comment by Mfa1m3** [comment]
We were able to solve it.
