### ISSUE TITLE
py2.7 -> py3.7

### ISSUE THREAD

**Issue by robmarkcole** [Terabee/sample_codes#2]
Hi
I have verified that the py2.7 file`Evo_Thermal_sample.py` runs fine with my hardweare but I am running a python 3.7 stack on an RPi. I kindly request that you publish a py3.7 branch.
Thanks

**Comment by pl-kabaradjian** [comment]
Hello @robmarkcole thanks for raising the issue,
Migrating to python3 is in our backlog but is not a priority for the moment so no promises ;) However, we will try to review and merge related pull requests whenever possible.
Cheers

**Comment by robmarkcole** [comment]
Thanks for the info, I will close this 'issue' :)
