### ISSUE TITLE
Very low FPS using Evo_64px_sample_py3.py

### ISSUE THREAD

**Issue by robmarkcole** [Terabee/sample_codes#6]
Hi
the specs state the device can run up to 160 Hz but with this script I am logging 3 FPS on mac and only 1FPS on a pi. Any advice?
Thanks

**Comment by pl-kabaradjian** [comment]
Hi @robmarkcole ,

The fps depends mostly on the mode of the sensor and the distance at which the sensor is looking, hence the "up to" on our spec sheet. The closer the target, the faster the update rate.You can test this easily by putting something close to it.

More details [here](https://www.terabee.com/wp-content/uploads/2019/03/TeraRanger-Evo-64px-Specification-sheet-2.pdf) on the spec sheet that is on our website.

If you want more specific details please feel free to contact our support [here](https://www.terabee.com/contact/).

Cheers,
