### ISSUE TITLE
Set emissivity command not being acknowledged for Evo Thermal using python

### ISSUE THREAD

**Issue by paraggadkari** [Terabee/sample_codes#8]
We are trying to send the following command for setting emissivity of the sensor (0.92)
- 0x00 0x51 0x02 0x5C 0xF6
But the sensor is not acknowledging the command. Is there anything wrong with our understanding of the 0x51 command?

Thanks,
Parag Gadkari

**Comment by vanrajbrown** [comment]
> We are trying to send the following command for setting emissivity of the sensor (0.92)
> 
> * 0x00 0x51 0x02 0x5C 0xF6
>   But the sensor is not acknowledging the command. Is there anything wrong with our understanding of the 0x51 command?
> 
> Thanks,
> Parag Gadkari

What is 0x02 in this command? I am facing the same error, but I am using this command - 0x00, 0x51, 0x44, 0xBE 
According to user manual setting custom emissivity the command used is this - 0x00 51 AA BB*
where AA is the emissivity value and BB is crc8 depending upon AA

**Comment by pl-kabaradjian** [comment]
Hello @vanrajbrown 

I confirm that 0x00 51 AA BB is the correct command to set the emissivity. From a quick check [here](https://crccalc.com/?crc=005144&method=crc8&datatype=hex&outtype=hex), it looks like you are not using the correct CRC: 0xC2 in your case.

Also, another way of setting the emissivity is to use the Windows GUI.

In the case you need additional help, I invite you to contact our support team [here](https://www.terabee.com/contact/)

Have a nice day,

**Comment by vanrajbrown** [comment]
> Hello @vanrajbrown
> 
> I confirm that 0x00 51 AA BB is the correct command to set the emissivity. From a quick check [here](https://crccalc.com/?crc=005144&method=crc8&datatype=hex&outtype=hex), it looks like you are not using the correct CRC: 0xC2 in your case.
> 
> Also, another way of setting the emissivity is to use the Windows GUI.
> 
> In the case you need additional help, I invite you to contact our support team [here](https://www.terabee.com/contact/)
> 
> Have a nice day,

Thanks for the reply, when using your crc the emissivity value is getting changed in the sensor although I am still getting the command not acknowledged message. I have confirmed the emissivity level change from the GUI application.

**Comment by pl-kabaradjian** [comment]
Thanks for the feedback, if the value changes in the GUI it means that it was correctly applied by the sensor. It can be confirmed by having higher temperature measurements when lowering the emissivity.
Doesn't change the fact he sensor should send an ACK.

In any case, I will pass this issue internally so we can have a look at this issue.

Have a nice day,
